version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    errcheck:
      exclude-functions:
        - (*go.uber.org/zap.Logger).Sync
        - (net/http.ResponseWriter).Write
        - (*encoding/json.Encoder).Encode
        - (io.Closer).Close
        - io.WriteString
