apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argus-gcc-ae

resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: argus-config
    patch: |
      - op: replace
        path: /data/ARGUS_COMPLIANCE_PROFILE
        value: "gcc-ae"
      - op: replace
        path: /data/ARGUS_STORAGE_REGION
        value: "ae-abudhabi-1"
      - op: replace
        path: /data/ARGUS_AIR_GAP
        value: "true"
      - op: replace
        path: /data/ARGUS_PII_PROFILE
        value: "gcc-ae"
      - op: replace
        path: /data/ARGUS_DATA_TIER_DEFAULT
        value: "3"
      - op: replace
        path: /data/ARGUS_LOCALE
        value: "ar"

  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: g42-registry
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never

commonLabels:
  argus.io/region: ae
  argus.io/compliance: nesa
  argus.io/environment: production
